spring:

  # spring config
  main:
    banner-mode: off

  # database config
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_management
    username: his_admin
    password: admin@123
    driver-class: com.mysql.cj.jdbc.Driver

  # JPA configurations
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true

# logging config
logging:
  level:
    org.springframework.web: DEBUG